name: Build Electron Apps

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact: "*.AppImage"
            artifact_name: "musicd-linux"
          - os: windows-latest
            artifact: "*.exe"
            artifact_name: "musicd-windows"
          ## Building the macOS version is currently disabled since github jacked up their prices.
          # - os: macos-latest
          #   artifact: "*.dmg"
          #   artifact_name: "musicd-macos"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 1

      - name: Git LFS Pull
        run: git lfs pull

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Enable Corepack
        run: corepack enable

      - name: Build frontend assets
        run: make frontend

      - name: Build Electron app
        run: make electron-build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}-${{ github.ref_name }}
          path: frontend/dist-electron/${{ matrix.artifact }}
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 1

      - name: Git LFS Pull
        run: git lfs pull

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
